language: node_js
node_js:
  - '20'

install:
  - npm install
  - npm install -g typescript

script:
  - npm run build
  - npm test

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
  skip_cleanup: true