name: CI/CD API

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: NPM install, build and test
        run: |
          npm install
          npm run
          npm test

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: bounceapp/render-action@0.6.0
        with:
          api-key: ${{ secrets.RENDER_APY_KEY }}
